### PR TITLE
Merge to master to ship latest version

### PR DESCRIPTION
**Pull request by ehoogerbeets**
### Checklist

* [ ] At least one test case is included for this feature or bug fix.
* [ ] `ReleaseNotes` has added or is not needed.
* [ ] This PR has passed all of the test cases on `Nodejs` and `Chrome Browser`.
* [ ] This PR has passed all of the test cases on `QT/QML`.
* [ ] This is an API breaking change.
* [ ] Requires a major version change.

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Links
[//]: # (Related issues, references)

### CODE REVIEW

**Comment by gouniLee** [comment]
not including https://github.com/iLib-js/iLib/pull/379 PR?

**Comment by ehoogerbeets** [comment]
We can add it to this PR once it is merged

**Review by gouniLee — APPROVED** [review]
Confirmed. All test is passed on Qt version 6.2.2 (QMake version 3.1) and Chrome browser test is passed on my machine (Asia/Seoul timezone)

**Comment by gouniLee** [comment]
wait. I think it would be better not to release the iLib now. There is an issue regarding dateformat/sysres json data including cldr 41 changes.

**Comment by gouniLee** [comment]
Confirmed. All test is passed on **Qt version 6.3.0 (QMake version 3.1)** and the Chrome browser test is passed on my machine (Asia/Seoul timezone)

**Comment by ehoogerbeets** [comment]
All unit tests pass on Chrome and Firefox on Ubuntu linux.
All unit tests pass on Chrome and Firefox on MacOS.
3 unit tests fail on Safari on Mac.
4 unit tests fail on Opera on Mac.

Failing tests are all related to the usage of the Intl object.

PR to fix this to follow this.

**Comment by ehoogerbeets** [comment]
Wow, Opera is so screwed up. It literally takes 10x longer to run these tests on Opera than on all the other browsers.

**Comment by gouniLee** [comment]
> Wow, Opera is so screwed up. It literally takes 10x longer to run these tests on Opera than on all the other browsers.

Is it slower than previous opera browser tests? because of adopting the Intl object work?

**Comment by ehoogerbeets** [comment]
Okay, now works on Chrome, Firefox, Opera, and Safari on Linux or MacOS as well.
I will merge this now! (finally!)

**Comment by gouniLee** [comment]
> Okay, now works on Chrome, Firefox, Opera, and Safari on Linux or MacOS as well. I will merge this now! (finally!)

finally! :) 👏👏👏

**Pull request merged**
