### PR TITLE
Fix unit formatting

### PR DESCRIPTION
**Pull request by ehoogerbeets**
This PR is ready for review now. Read the changes to docs/tutorial/units.md first to get an idea of what the whole change is before looking at the code.

### CODE REVIEW

**Comment by gouniLee** [comment]
It looks like big change. and It would be nicer to give more accurate formatting for users. :) 
For unformatting, iLib gets data from CLDR. and CLDR defined 3 lengths (narrow, short and long) but the iLib doesn't use narrow length for unit formatting. Is there any you intention? Because other feature uses narrow data from CLDR.

**Comment by gouniLee** [comment]
Oh! Have you run test cases on QT/QML? It fails some cases in `unit` and `util` category.

**Comment by ehoogerbeets** [comment]
All Qt tests are fixed now. Please try again.

**Comment by gouniLee** [comment]
Yes, regarding my question, it is not tightly related this PR. I just found that while looking UniFmt code.
I checked All of cased are Passed on QT/QML. Thanks!

**Pull request merged**
