### PR TITLE
Merge to master to publish v14.17.0

### PR DESCRIPTION
**Pull request by ehoogerbeets**
### Checklist

* [ ] At least one test case is included for this feature or bug fix.
* [x] `ReleaseNotes` has added or is not needed.
* [x] This PR has passed all of the test cases on `Nodejs` and `Chrome Browser`.
* [x] This PR has passed all of the test cases on `QT/QML`.
* [ ] This is an API breaking change.
* [ ] Requires a major version change.

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Links
[//]: # (Related issues, references)

### CODE REVIEW

**Review by gouniLee — APPROVED** [review]
Approved. 
 All the test cases are passed on QT v6.4.0 as well.

**Comment by ehoogerbeets** [comment]
This should be retested on QT before we merge.

**Comment by gouniLee** [comment]
ah...  there's one test fail case in both qt and browser tool (I missed this case before)
It's a newly activated case regarding calendar conversion. 
https://github.com/iLib-js/iLib/blob/development/js/test/date/testdatefmt_es_CO.js#L275
It expects "2011-10-11". maybe due to my timezone...?

**Comment by gouniLee** [comment]
and the option is a typo. should be `calendar` not lendar
https://github.com/iLib-js/iLib/blob/development/js/test/date/testdatefmt_es_CO.js#L263

after I fixed it, the expected result become different as '2011-09-29' (node) and '2011-09-28'(browser/qt)

**Comment by gouniLee** [comment]
All of the tests is passed on Qt v6.4.0 and v6.2.2
and chrome browser v102 (102.0.5005.115) and v109 (109.0.5414.119)

**Pull request merged**
