### PR TITLE
Merge to master to publish 14.8.0

### PR DESCRIPTION
**Pull request by ehoogerbeets**
### Checklist

* [ ] At least one test case is included for this feature or bug fix.
* [x] `ReleaseNotes` has added or is not needed.
* [x] This PR has passed all of the test cases on `Nodejs` and `Chrome Browser`.
* [x] This PR has passed all of the test cases on `QT/QML`.
* [ ] This is an API breaking change.
* [ ] Requires a major version change.

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Links
[//]: # (Related issues, references)

### CODE REVIEW

**Review by gouniLee — APPROVED** [review]
All test is passed on Qt version 5.12.4 (QMake version 3.1)

**Comment by gouniLee** [comment]
@ehoogerbeets Please merge it and release the new version

**Comment by ehoogerbeets** [comment]
I didn't merge it previously because I had problems running all the web tests. After rebooting my computer, everything worked fine, so now I can publish. (Not sure what was happening there...)

**Comment by gouniLee** [comment]
> I didn't merge it previously because I had problems running all the web tests. After rebooting my computer, everything worked fine, so now I can publish. (Not sure what was happening there...)

oh.. To make sure, I ran the all test on my chrome browser. and Everything works fine.

**Pull request merged**
