### PR TITLE
Update date/time format data as sync up CLDR v30

### PR DESCRIPTION
**Pull request by gouniLee**
>  Hopefully this changes could  be applied when ilib 12 is released. 
>  All of legacy test are not fixed.

* clock.jf, dateformats.json and sysres.json files are updated as sync up CLDR 30.
* Fix unittest failures in regards to data (DateFmt, DurationFmt, DateRange) is changed and Make passed them all.
* The cldr json data is grouped into packaged by functionality since v27.  including  a major clean up effort. so Converting tool codes is updated too. https://github.com/unicode-cldr/cldr-json.
* Regarding LG webOSTV support locales, I did manual QA internally.

### CODE REVIEW

**Comment by ehoogerbeets** [comment]
Unit tests fail:

Dublin:~/ht/ilib2/js> ant test.dynamic.compiled
Buildfile: /mnt/Terasaur/root/home/edwin/ht/ilib2/js/build.xml

test.dynamic.compiled:
     [exec] Only running test util
     [exec] Running compiled dynamic suites: ["util"]
     [exec] Summary - 215 tests run, 215 pass, 0 fail, 0.364 seconds.
     [exec] Only running test .
     [exec] Running compiled dynamic suites: ["."]
     [exec] Summary - 1915 tests run, 1915 pass, 0 fail, 1.098 seconds.
     [exec] Only running test calendar
     [exec] Running compiled dynamic suites: ["calendar"]
     [exec] Summary - 1706 tests run, 1706 pass, 0 fail, 1.352 seconds.
     [exec] Only running test date1
     [exec] Running compiled dynamic suites: ["date1"]
     [exec] Summary - 2217 tests run, 2217 pass, 0 fail, 1.872 seconds.
     [exec] Only running test date2
     [exec] Running compiled dynamic suites: ["date2"]
     [exec] fs.js:641
     [exec]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
     [exec]                  ^
     [exec] 
     [exec] Error: ENOENT: no such file or directory, open 'date/test/testdatefmt_km_KH.js'
     [exec]     at Error (native)
     [exec]     at Object.fs.openSync (fs.js:641:18)
     [exec]     at Object.fs.readFileSync (fs.js:509:33)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:27:19)
     [exec]     at Object.runTests (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:206:4)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:222:17)
     [exec]     at Array.forEach (native)
     [exec]     at Object.runTests (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:217:18)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:222:17)
     [exec]     at Array.forEach (native)
     [exec] Result: 1
     [exec] Only running test date3
     [exec] Running compiled dynamic suites: ["date3"]
     [exec] Summary - 1659 tests run, 1659 pass, 0 fail, 0.785 seconds.
     [exec] Only running test daterange1
     [exec] Running compiled dynamic suites: ["daterange1"]
     [exec] fs.js:641
     [exec]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
     [exec]                  ^
     [exec] 
     [exec] Error: ENOENT: no such file or directory, open 'daterange/test/testdatefmtrange_km_KH.js'
     [exec]     at Error (native)
     [exec]     at Object.fs.openSync (fs.js:641:18)
     [exec]     at Object.fs.readFileSync (fs.js:509:33)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:27:19)
     [exec]     at Object.runTests (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:206:4)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:222:17)
     [exec]     at Array.forEach (native)
     [exec]     at Object.runTests (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:217:18)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:222:17)
     [exec]     at Array.forEach (native)
     [exec] Result: 1
     [exec] Only running test daterange2
     [exec] Running compiled dynamic suites: ["daterange2"]
     [exec] Summary - 636 tests run, 636 pass, 0 fail, 0.655 seconds.
     [exec] Only running test daterange3
     [exec] Running compiled dynamic suites: ["daterange3"]
     [exec] Summary - 575 tests run, 575 pass, 0 fail, 0.717 seconds.
     [exec] Only running test durfmt
     [exec] Running compiled dynamic suites: ["durfmt"]
     [exec] fs.js:641
     [exec]   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
     [exec]                  ^
     [exec] 
     [exec] Error: ENOENT: no such file or directory, open 'durfmt/test/testdurfmt_km_KH.js'
     [exec]     at Error (native)
     [exec]     at Object.fs.openSync (fs.js:641:18)
     [exec]     at Object.fs.readFileSync (fs.js:509:33)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:27:19)
     [exec]     at Object.runTests (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:206:4)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:222:17)
     [exec]     at Array.forEach (native)
     [exec]     at Object.runTests (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:217:18)
     [exec]     at Object.<anonymous> (/mnt/Terasaur/root/home/edwin/ht/ilib2/js/test/TestSuiteModule.js:222:17)
     [exec]     at Array.forEach (native)
     [exec] Result: 1
     [exec] Only running test number
     [exec] Running compiled dynamic suites: ["number"]
     [exec] Summary - 743 tests run, 743 pass, 0 fail, 0.531 seconds.
     [exec] Only running test maps
     [exec] Running compiled dynamic suites: ["maps"]
     [exec] Summary - 138 tests run, 138 pass, 0 fail, 0.955 seconds.
     [exec] Only running test ctype
     [exec] Running compiled dynamic suites: ["ctype"]
     [exec] Summary - 253 tests run, 253 pass, 0 fail, 0.339 seconds.
     [exec] Only running test strings-ext
     [exec] Running compiled dynamic suites: ["strings-ext"]
     [exec] Summary - 81 tests run, 81 pass, 0 fail, 12.579 seconds.
     [exec] Only running test phone1
     [exec] Running compiled dynamic suites: ["phone1"]
     [exec] Summary - 730 tests run, 730 pass, 0 fail, 0.518 seconds.
     [exec] Only running test phone2
     [exec] Running compiled dynamic suites: ["phone2"]
     [exec] Summary - 833 tests run, 833 pass, 0 fail, 0.374 seconds.
     [exec] Only running test phone3
     [exec] Running compiled dynamic suites: ["phone3"]
     [exec] Summary - 912 tests run, 912 pass, 0 fail, 0.418 seconds.
     [exec] Only running test units
     [exec] Running compiled dynamic suites: ["units"]
     [exec] Summary - 544 tests run, 544 pass, 0 fail, 0.773 seconds.
     [exec] Only running test name
     [exec] Running compiled dynamic suites: ["name"]
     [exec] Summary - 1045 tests run, 1045 pass, 0 fail, 0.945 seconds.
     [exec] Only running test address1
     [exec] Running compiled dynamic suites: ["address1"]
     [exec] Summary - 408 tests run, 408 pass, 0 fail, 1.096 seconds.
     [exec] Only running test address2
     [exec] Running compiled dynamic suites: ["address2"]
     [exec] Summary - 371 tests run, 371 pass, 0 fail, 0.823 seconds.
     [exec] Only running test address3
     [exec] Running compiled dynamic suites: ["address3"]
     [exec] Summary - 674 tests run, 674 pass, 0 fail, 1.283 seconds.
     [exec] Only running test collate
     [exec] Running compiled dynamic suites: ["collate"]
     [exec] Summary - 794 tests run, 794 pass, 0 fail, 20.027 seconds.

BUILD SUCCESSFUL
Total time: 54 seconds

**Comment by ehoogerbeets** [comment]
Looks like you forgot to check in some files?

**Comment by gouniLee** [comment]
Yes, I missed some test files regarding km-KH, si-LK and sw-KE locales. These are newly support locale for webOS TV.

**Comment by ehoogerbeets** [comment]
All tests pass now. Merging...

**Pull request merged**
