### PR TITLE
Webpack support

### PR DESCRIPTION
**Pull request by ehoogerbeets**
New webpack support.

This depends on the new ilib-webpack-loader for webpack, which is in a separate repo.

The assembly tool is no longer used. Webpack is used to assemble ilib both for the web and for node, and the loader can be used to assemble a custom version of ilib for your own web app. The readme for the ilib-webpack-loader repo has more details on how that all works.

This branch supports assembled (all data and code in one file), dynamic data (code in one file, but the data in separate files that are loaded dynamically), and dynamic modes (all code and data loaded dynamically). It also supports synchronous and asynchronous mode for each mode, even on the web. This is not tested on webOS or enact yet.

All unit tests pass in all modes on nodejs, chrome, safari, and firefox on the mac and on nodejs, chrome, and firefox on ubuntu. Windows has not been tested yet.

### CODE REVIEW

**Comment by gouniLee** [comment]
Hm. When I'm running 'ant full build' it fails because of 'uglify-js' Of course I did 'npm install' before running ant build. I've tried few ways to make it work. but It didn't work. Was it ok on your machine?
```
java.io.IOException: Cannot run program "uglifyjs" (in directory "/home/goun/Source/opensource_iLib/webpack2/js"): error=2, No such file or directory

```
and During builds It shows some warning message as below in Factory method.  Is it ok to be ignored?
It also happend when I'm testing 'ilib-webpack-loader'
```
[exec] WARNING in ./lib/CalendarFactory.js
     [exec] 143:34-53 Critical dependency: the request of a dependency is an expression
     [exec]  @ ./lib/CalendarFactory.js
     [exec]  @ ./lib/metafiles/ilib-standard-webpack.js
     [exec] 
     [exec] WARNING in ./lib/DateFactory.js
     [exec] 178:31-50 Critical dependency: the request of a dependency is an expression
     [exec]  @ ./lib/DateFactory.js
     [exec]  @ ./lib/metafiles/ilib-standard-webpack.js
```

**Comment by gouniLee** [comment]
I have no idea why a testing  result is a difference between Travis and my machine. But I got many tests are failed in `root: test.assemble.uncompiled.nu' so Test is terminated at this time. Any idea?
```
[exec] root: .....FFFFFFFF...FF..FFFF.F..F..FFFFFF.F....F....................................................................................................................FF.........FF....F.FF..FF..FF....F...F..F...F..F...F..F...F..F...F..FFFFF.FFFFFF.FFFF.F..FFF.F..FFFFF.FFFF........F..FFFFF.FFFF.F..FFFFFFFFFFFFFFFFFFF.FFFF.F..FFF.F..FFF....FFF.F..FFFFF.FFFFFF.FF...F......FF.F..F...FF.F..F......F..F......F..F...FFFFFFF...FFF.FFF...FFF.FFF...........F....F..F...FF........FFFF.FF...FF.F..F.....F..F......F..F.F.FFFF.FF...FF.F..F...FFF.FF...FFFF.FF...FF.F..F...FFF..F....FFFFFFF...FFF.FFF...FF.F..F.............FFFFFFF...FFFF.FF...FFFF.FF....F..F.....FFFF.FF...FFFF.FF...FFFF.FF...FFFF.FF...FFFF.FF......F..F...FFFF.FF................FFFF......F..F.F.FF.F..F...FF........FF.F..F....F....F...FF.F..F...FFFF.FF...FF.F..F......FFF.FFF.F........................F..F...FF.F..F...FFFFFFF.............FF.F..F................F..F...FF..................FF.F..F...FF....F...FF....F...FF....F....FF........FF...........F.F...FF........FFF.FFF.F.FF.F..F...FF.F..F...FF.F..F...FF.F..F...FF.F..F......FF.F..F...FF.F..F...FFFF.FF...FFFF.FF...FFFF.FF...FF.F..F......F..F...FFFF.FF...FFFFFFF.....F..F......F..F...FF.F..F...FF.F..F...FF.F..F...FF.F..F...FF.F..F...FF.F..F...FF.F.......F........FFFFFFF......F..F...........F.........F.........F....F..F...FF.F..F.......FFF.......FFF.......FFF...FFF.FFF...FF.F..F......F..F...FF...........F..F......F..F......F..F......F..F...FF........FF.F..F......F..F......F..F....FF...F.....F.F.F.FF.F.F.FFFFFF...FFF.FF...FFFFFFFFFFFFFFFFFFF...F.FF.FFFF......F.FF.FFFF.FFFF.F.FFFFFFFFFFFFFFF.FFFFFFFFFF.....FFFF.F.FFFFFFFFFFFFFFFFF.FF.........................FFFFFFFFFFFFFFFFFFFFFFFFFF.......................FFF..............FFFFFFF.....F.FFFF.....FFF.......F......FFFFFFFFFFFFFFF................................................................FFFFFFFFFFF.............................................................................................................................FFF.FFFF.F...FFFFFFFFF.F.FF...F.FF.FF.....FF..FF..FFFF....FF..FFF...F..FFFFFFFFFFF...FF
```

**Comment by ehoogerbeets** [comment]
Make sure that the <root-of-ilib>/node_modules/.bin directory is in your path.

**Comment by ehoogerbeets** [comment]
Also, did you try "ant clean" first before building? Sometimes old stuff is left over in the "locale" directory which gets included into the webpacked code and screws it up.

**Comment by gouniLee** [comment]
I've faced many errors while running  Nodejs and Browser. It looks like missing locale data.   

and testing with Browser,
for a browser, It uses `/output/js/ut-assembled-uncompiled-web/ilib-ut.js"` file, but it doesn't include locale data. so iLib functions could return a correct value. 

Here'are examples of many failures while running   `test.assembled.uncompiled.nu:' 
```
     [exec] AssertionError: '01:45 - 02:30, 31/12/2011' == '2011年12月31日 下午1:45 – 下午2:30'
     [exec]     at Object.equal (/home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/lib/types.js:83:39)
     [exec]     at Object.testDateRngFmtTWRangeInDayFull (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:184:17), <anonymous>:137:14)
     [exec]     at /home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/lib/core.js:232:20
     [exec]     at /home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:168:13
     [exec]     at /home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:131:25
     [exec]     at /home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:165:17
     [exec]     at /home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:463:34
     [exec]     at Object.setUp (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:184:17), <anonymous>:33:9)
     [exec]     at /home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/lib/core.js:260:35
     [exec]     at /home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:458:21
     [exec]     at /home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:163:13
     [exec]     at iterate (/home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:123:13)
     [exec]     at async.forEachSeries (/home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:139:9)
     [exec]     at _asyncMap (/home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:162:9)
     [exec]     at Object.mapSeries (/home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:152:23)
     [exec]     at Object.async.series (/home/goun/Source/opensource_iLib/webpack/js/node_modules/nodeunit/deps/async.js:456:19)
```
```
     [exec] TypeError: Cannot read property 'fields' of undefined
     [exec]     at Object._parseAddress (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21956:26)
     [exec]     at Object.eval (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21897:13)
     [exec]     at Object.Utils.loadData (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:2230:4)
     [exec]     at Object.eval (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21889:12)
     [exec]     at Object.Utils.loadData (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:2230:4)
     [exec]     at Object._init (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21880:9)
     [exec]     at Object._determineDest (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21872:8)
     [exec]     at Object.eval (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21804:10)
     [exec]     at Object.Utils.loadData (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:2230:4)
     [exec]     at Object._loadCtrynames (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21797:9)
     [exec]     at Object.eval (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21785:11)
     [exec]     at Object.Utils.loadData (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:2230:4)
     [exec]     at Object._loadCountries (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21776:10)
     [exec]     at Object.eval (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21758:13)
     [exec]     at Object.Utils.loadData (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:2230:4)
     [exec]     at Object.eval (eval at <anonymous> (/home/goun/Source/opensource_iLib/webpack/js/test/testRunner.js:141:5), <anonymous>:21749:12)
```

**Comment by gouniLee** [comment]
The latest of your changes make an error.
```
assemble.unittest.assembled.node:
     [echo] executing webpack
     [exec] Hash: 6df9d3f71f7a533e86b1
     [exec] Version: webpack 3.11.0
     [exec] Time: 35ms
     [exec] 
     [exec] ERROR in Entry module not found: Error: Can't resolve 'ilib-webpack-loader' in '/home/goun/Source/opensource_iLib/webpack_new/js'
     [exec] Result: 2
     [echo] executing webpack
     [exec] Hash: 037ca495aa4cd016dc33
     [exec] Version: webpack 3.11.0
     [exec] Time: 37ms
     [exec] 
     [exec] ERROR in Entry module not found: Error: Can't resolve 'ilib-webpack-loader' in '/home/goun/Source/opensource_iLib/webpack_new/js'
     [exec] Result: 2

test.assembled.uncompiled.nu:
     [exec] Testing all suites.
     [exec] Running uncompiled assembled sync suites: ["util","root","calendar","date","daterange","durfmt","number","maps","ctype","strings-ext","phone","units","name","address","collate"]
     [exec] loading in ../output/js/ut-assembled-uncompiled-node/ilib-ut.js
     [exec] Error: ENOENT: no such file or directory, open '../output/js/ut-assembled-uncompiled-node/ilib-ut.js'
     [exec]     at Object.fs.openSync (fs.js:646:18)
     [exec]     at Object.fs.readFileSync (fs.js:551:33)
     [exec]     at Object.<anonymous> (/home/goun/Source/opensource_iLib/webpack_new/js/test/testRunner.js:140:21)
     [exec]     at Module._compile (module.js:643:30)
     [exec]     at Object.Module._extensions..js (module.js:654:10)
     [exec]     at Module.load (module.js:556:32)
     [exec]     at tryModuleLoad (module.js:499:12)
     [exec]     at Function.Module._load (module.js:491:3)
     [exec]     at Function.Module.runMain (module.js:684:10)
     [exec]     at startup (bootstrap_node.js:187:16)
     [exec]     at bootstrap_node.js:608:3

BUILD FAILED

```

**Comment by gouniLee** [comment]
It still shows a same error message that I attached above. It looks like installed ilib-webpack-loader package through  `package.json` doesn't have ilib-webpack-loader file.

**Comment by gouniLee** [comment]
Have you tried to run tests on QT/QML. Build fails while `run.qmake` target.
But I confirmed every tests passed on nodejs and browser on Linux

**Comment by gouniLee** [comment]
fyi. How about to add the explanation regarding below? 

```
export NODE_OPTIONS="--max-old-space-size=3072"
```
I integrate this branch to my gruntBuild work branch. and I've faced errors below on my linux machine.

```
[exec] <--- Last few GCs --->
     [exec] 
     [exec] FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
     [exec]  1: node::Abort() [/usr/local/bin/node]
     [exec]  2: 0x128059c [/usr/local/bin/node]
     [exec]  3: v8::Utils::ReportOOMFailure(char const*, bool) [/usr/local/bin/node]
     [exec]  4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
     [exec]  5: v8::internal::Factory::NewByteArray(int, v8::internal::PretenureFlag) [/usr/local/bin/node]
     [exec]  6: v8::internal::TranslationBuffer::CreateByteArray(v8::internal::Factory*) [/usr/local/bin/node]
     [exec] [28386:0x3274210]    24869 ms: Mark-sweep 1404.2 (1455.8) -> 1404.2 (1432.3) MB, 941.1 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 941 ms) last resort GC in old space requested 7: v8::internal::compiler::CodeGenerator::PopulateDeoptimizationData(v8::internal::Handle<v8::internal::Code>) [/usr/local/bin/node]
     [exec] 
     [exec]  8: v8::internal::compiler::CodeGenerator::FinalizeCode() [/usr/local/bin/node]
     [exec] [28386:0x3274210]    25816 ms: Mark-sweep 1404.2 (1432.3) -> 1404.2 (1432.3) MB, 947.1 / 0.0 ms  last resort GC in old space requested
     [exec]  9: v8::internal::compiler::PipelineImpl::FinalizeCode() [/usr/local/bin/node]
     [exec] 
     [exec] 
     [exec] <--- JS stacktrace --->10: v8::internal::compiler::PipelineCompilationJob::FinalizeJobImpl() [/usr/local/bin/node]
     [exec] 
     [exec] 11: v8::internal::Compiler::FinalizeCompilationJob(v8::internal::CompilationJob*) [/usr/local/bin/node]
```

**Comment by ehoogerbeets** [comment]
The NODE_OPTIONS change to the .travis.yml tells node to allocate more heap memory for the v8 javascript engine. The default on travis is 1 gb and that was not enough, apparently, so I changed it to be 3 gb. The virtual machine instance I think only has 4 or 6gb. Webpack kept failing with the same error that you are getting in the grunt branch. If you are seeing that error, try setting the NODE_OPTIONS in the same way before running grunt. If it works, then we need to change the instructions in docs/Installation.md to tell people to do the same thing. (Also probably docs/FAQ.md)

**Comment by gouniLee** [comment]
The issue was fixed by setting node option. I've added an option in `.bashrc` file in my machine. I'll also add it in grunt file in order not to fail a build. I think it is a good idea to add instruction in .md file

**Pull request merged**
