### PR TITLE
Added node 18 to the circleci tests

### PR DESCRIPTION
**Pull request by ehoogerbeets**
### Checklist

* [ ] At least one test case is included for this feature or bug fix.
* [ ] `ReleaseNotes` has added or is not needed.
* [ ] This PR has passed all of the test cases on `Nodejs` and `Chrome Browser`.
* [ ] This PR has passed all of the test cases on `QT/QML`.
* [ ] This is an API breaking change.
* [ ] Requires a major version change.

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Links
[//]: # (Related issues, references)

### CODE REVIEW

**Comment by ehoogerbeets** [comment]
Note that the unit tests fail on node 18 because of the updated version of ICU, so we have to update those here

**Comment by gouniLee** [comment]
> Note that the unit tests fail on node 18 because of the updated version of ICU, so we have to update those tests here

I was trying to run a test cases witth node v18.14 on my desktop. but the build fails with the following errors..
```
assemble.unittest.assembled.node:
     [echo] executing webpack
     [exec] Error: error:0308010C:digital envelope routines::unsupported
     [exec]     at new Hash (node:internal/crypto/hash:71:19)
     [exec]     at Object.createHash (node:crypto:133:10)
     [exec]     at module.exports (/home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/util/createHash.js:135:53)
     [exec]     at NormalModule._initBuildHash (/home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/NormalModule.js:417:16)
     [exec]     at handleParseError (/home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/NormalModule.js:471:10)
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/NormalModule.js:503:5
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/NormalModule.js:358:12
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:373:3
     [exec]     at iterateNormalLoaders (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
     [exec]     at iterateNormalLoaders (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:236:3
     [exec]     at runSyncOrAsync (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
     [exec]     at iterateNormalLoaders (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
     [exec]     at Array.<anonymous> (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
     [exec]     at Storage.finished (/home/goun/Source/opensource_iLib/develop/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/graceful-fs/graceful-fs.js:123:16
     [exec]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
     [echo] executing webpack
     [exec] Error: error:0308010C:digital envelope routines::unsupported
     [exec]     at new Hash (node:internal/crypto/hash:71:19)
     [exec]     at Object.createHash (node:crypto:133:10)
     [exec]     at module.exports (/home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/util/createHash.js:135:53)
     [exec]     at NormalModule._initBuildHash (/home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/NormalModule.js:417:16)
     [exec]     at handleParseError (/home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/NormalModule.js:471:10)
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/NormalModule.js:503:5
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/webpack/lib/NormalModule.js:358:12
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:373:3
     [exec]     at iterateNormalLoaders (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
     [exec]     at iterateNormalLoaders (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:236:3
     [exec]     at runSyncOrAsync (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
     [exec]     at iterateNormalLoaders (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
     [exec]     at Array.<anonymous> (/home/goun/Source/opensource_iLib/develop/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
     [exec]     at Storage.finished (/home/goun/Source/opensource_iLib/develop/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
     [exec]     at /home/goun/Source/opensource_iLib/develop/node_modules/graceful-fs/graceful-fs.js:123:16
     [exec]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)

test.assembled.uncompiled:
     [exec] Testing all suites.
     [exec] Running uncompiled assembled sync suites: ["util","root","calendar","date","daterange","durfmt","number","maps","ctype","strings-ext","phone","units","name","address","collate"]
     [exec] loading in ../output/js/ut-assembled-uncompiled-node/ilib-ut.js
     [exec] Error: ENOENT: no such file or directory, open '../output/js/ut-assembled-uncompiled-node/ilib-ut.js'
     [exec]     at Object.openSync (node:fs:600:3)
     [exec]     at Object.readFileSync (node:fs:468:35)
     [exec]     at Object.<anonymous> (/home/goun/Source/opensource_iLib/develop/js/test/testRunner.js:149:21)
     [exec]     at Module._compile (node:internal/modules/cjs/loader:1226:14)
     [exec]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
     [exec]     at Module.load (node:internal/modules/cjs/loader:1089:32)
     [exec]     at Function.Module._load (node:internal/modules/cjs/loader:930:12)
     [exec]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
     [exec]     at node:internal/main/run_main_module:23:47

BUILD FAILED
/home/goun/Source/opensource_iLib/develop/js/build.xml:752: The following error occurred while executing this line
```

**Comment by ehoogerbeets** [comment]
The build problems are resolved and the webpack problem is resolved. However, 3 unit tests still fail on Chrome 110. And, it seems to fail as if it were at cldr 42 because the results look like the ones on nodejs. I am trying to find a way to figure out what the cldr version is in browsers, but there does not seem to be a standard way. Maybe we can just map the browser version number to a CLDR version number, but then again, I can't find a table of them. Grrr!

**Review by gouniLee — APPROVED** [review]

**Comment by ehoogerbeets** [comment]
I'm going to merge this one, as the goal of the PR is to support node 18, which does work fine. We'll have to come up with a separate PR to fix the problems in Chrome, which are a separate issue.

**Pull request merged**
