### PR TITLE
Merge to main to publish v14.21.0

### PR DESCRIPTION
**Pull request by ehoogerbeets**
### Checklist

* [ ] At least one test case is included for this feature or bug fix.
* [ ] `ReleaseNotes` has added or is not needed.
* [ ] This PR has passed all of the test cases on `Nodejs` and `Chrome Browser`.
* [ ] This PR has passed all of the test cases on `QT/QML`.
* [ ] This is an API breaking change.
* [ ] Requires a major version change.

### Issue Resolved / Feature Added
[//]: # (Describe the issue resolved or feature added by this pull request)

### Resolution
[//]: # (Does the code work as intended?)
[//]: # (What is the impact of this change and *why* was it made?)

### Links
[//]: # (Related issues, references)

### CODE REVIEW

**Comment by ehoogerbeets** [comment]
Error in chrome unit tests:

```
testDateFmtSimpleLong_en_GB_useIntl_dmwy (1, 1, 2)
ok
equal Thursday 29 September 2011 (actual) != Thursday, 29 September 2011 (expected)
AssertionError
    at Object.equal (http://127.0.0.1:9090/test/nodeunit/nodeunit.js:1723:39)
    at Object.testDateFmtSimpleLong_en_GB_useIntl_dmwy (http://127.0.0.1:9090/test/date/testdatefmt_en_GB.js:306:18)
    at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:2060:20
    at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:666:13
    at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:629:25
    at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:663:17
    at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:961:34
    at Object.setUp (http://127.0.0.1:9090/test/date/testdatefmt_en_GB.js:40:9)
    at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:2088:35
    at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:956:21
```
I am using Chrome 131.0.6778.85

**Comment by gouniLee** [comment]
> Error in chrome unit tests:
> 
> ```
> testDateFmtSimpleLong_en_GB_useIntl_dmwy (1, 1, 2)
> ok
> equal Thursday 29 September 2011 (actual) != Thursday, 29 September 2011 (expected)
> AssertionError
>     at Object.equal (http://127.0.0.1:9090/test/nodeunit/nodeunit.js:1723:39)
>     at Object.testDateFmtSimpleLong_en_GB_useIntl_dmwy (http://127.0.0.1:9090/test/date/testdatefmt_en_GB.js:306:18)
>     at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:2060:20
>     at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:666:13
>     at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:629:25
>     at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:663:17
>     at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:961:34
>     at Object.setUp (http://127.0.0.1:9090/test/date/testdatefmt_en_GB.js:40:9)
>     at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:2088:35
>     at http://127.0.0.1:9090/test/nodeunit/nodeunit.js:956:21
> ```
> 
> I am using Chrome 131.0.6778.85

I made a PR to fix this issue. Please check here. https://github.com/iLib-js/iLib/pull/479

**Comment by ehoogerbeets** [comment]
The error was resolved.

**Comment by ehoogerbeets** [comment]
Please approve the PR

**Review by gouniLee — APPROVED** [review]
Approved. All of the tests are passed on Qt 6.6.1.

**Pull request merged**
